
  CREATE TABLE "CR"."HWM_COPY_LOG" 
   (	"OWNER" VARCHAR2(30 BYTE), 
	"SRC_TABLE" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"DST_TABLE" VARCHAR2(128 BYTE), 
	"COPIED_AT" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	"ERROR_MSG" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CR_DATA" ;

  CREATE INDEX "CR"."HWM_COPY_LOG_IX1" ON "CR"."HWM_COPY_LOG" ("OWNER", "SRC_TABLE", "OBJECT_NAME", "DST_TABLE", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CR_DATA" ;

