
  CREATE TABLE "HR"."HWM_LOG" 
   (	"LOG_ID" NUMBER, 
	"OWNER" VARCHAR2(100 BYTE), 
	"BASE_TABLE" VARCHAR2(1000 BYTE), 
	"OBJECT_NAME" VARCHAR2(4000 BYTE), 
	"OBJECT_TYPE" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"ERROR_MSG" VARCHAR2(4000 BYTE), 
	"DESC_TXT" VARCHAR2(4000 BYTE), 
	"ACTION_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 CONSTRAINT "CHK_STATUS_VALID" CHECK (STATUS IN ('SUCCESS', 'FAILED')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

